### ISSUE TITLE
Admin App: Reports and Notifications for Data Quality Reporting

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/servicesadvisor-3.0#51] opened 2017-02-23 17:17 UTC
for Somalia.  See https://github.com/PeaceGeeksSociety/SA-UNHCR-Somalia/issues/20

**Comment by mackh** [comment] 2017-03-02 21:56
duplicate of #30

**Closed by mackh** 2017-03-02 21:56 UTC
Labels: enhancement
